name: Create Pull Request to MusicBrainz Picard Plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'shelves/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: picard-plugin-shelves
      
      - name: Set up Git configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Clone MusicBrainz Picard Plugins repository
        env:
          GH_TOKEN: ${{ secrets.PICARD_PLUGINS_PAT }}
        run: |
          # Clone using authenticated URL
          git clone --branch 2.0 --single-branch \
            "https://x-access-token:${GH_TOKEN}@github.com/nrth3rnlb/picard-plugins.git" \
            picard-plugins
          
          cd picard-plugins
          echo "Cloned picard-plugins repository at commit:"
          git log -1 --oneline
      
      - name: Fetch and sync with upstream
        run: |
          cd picard-plugins
          echo "Fetching latest changes from upstream..."
          git fetch origin refs/heads/2.0
          
          echo "Current HEAD:"
          git log -1 --oneline
          
          echo "Latest commit on origin/2.0:"
          git log -1 --oneline origin/2.0
          
          # Check if we're behind upstream
          BEHIND=$(git rev-list --count HEAD..origin/2.0)
          echo "Commits behind upstream: $BEHIND"
          
          if [ "$BEHIND" -gt 0 ]; then
            echo "Repository is behind upstream. Pulling latest changes..."
            git pull origin 2.0
            echo "Successfully synchronized with upstream"
          else
            echo "Repository is already up-to-date with upstream"
          fi
          
          echo "Current state after sync:"
          git log -1 --oneline
      
      - name: Create feature branch
        run: |
          cd picard-plugins
          BRANCH_NAME="update-shelves-plugin-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "Created branch: $BRANCH_NAME"
      
      - name: Copy shelves plugin
        run: |
          cd picard-plugins
          
          # Remove existing shelves plugin if it exists
          if [ -d "plugins/shelves" ]; then
            echo "Removing existing shelves plugin..."
            rm -rf plugins/shelves
          fi
          
          # Copy the updated plugin
          echo "Copying shelves plugin from source repository..."
          cp -r ../picard-plugin-shelves/shelves plugins/shelves
          
          echo "Contents of plugins/shelves:"
          ls -la plugins/shelves/
      
      - name: Commit changes
        run: |
          cd picard-plugins
          git add plugins/shelves
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            git commit -m "Update shelves plugin" \
              -m "Updated shelves plugin from nrth3rnlb/picard-plugin-shelves" \
              -m "This automated update ensures the plugin is synchronized with the latest changes."
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
            echo "Changes committed successfully"
          fi
      
      - name: Push changes and create pull request
        if: env.HAS_CHANGES == 'true'
        env:
          GH_TOKEN: ${{ secrets.PICARD_PLUGINS_PAT }}
        run: |
          cd picard-plugins
          
          # Push the branch
          # replace the log line with something like:
          echo "Pushing branch to remote repository (nrth3rnlb/picard-plugins)..."
          
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/nrth3rnlb/picard-plugins.git
          git push origin "$BRANCH_NAME"
          
          # Create pull request using GitHub CLI
          echo "Creating pull request..."
          PR_BODY=$(cat << 'EOF'
          This pull request updates the shelves plugin to the latest version.
          
          **Changes:**
          - Updated plugin files from [nrth3rnlb/picard-plugin-shelves](https://github.com/nrth3rnlb/picard-plugin-shelves)
          - Synchronized with the latest upstream changes before applying updates
          
          **Verification:**
          - The upstream repository was verified to be up-to-date before copying changes
          - All plugin files have been copied and committed
          
          This is an automated pull request generated by GitHub Actions.
          EOF
          )
          
          echo gh pr create \
            --repo metabrainz/picard-plugins \
            --base 2.0 \
            --head "$BRANCH_NAME" \
            --title "Update shelves plugin" \
            --body "$PR_BODY"
      
      - name: Summary
        run: |
          echo "## Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "$HAS_CHANGES" == "true" ]; then
            echo "✅ Pull request created successfully" >> $GITHUB_STEP_SUMMARY
            echo "- Branch: \`$BRANCH_NAME\`" >> $GITHUB_STEP_SUMMARY
            echo "- Target: metabrainz/picard-plugins (2.0 branch)" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No changes detected - pull request not created" >> $GITHUB_STEP_SUMMARY
          fi
